version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/myschool
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/myschool:/app
      - DJANGO_SETTINGS_MODULE=school.settings
    command: python manage.py runserver 0.0.0.0:8000