# Generated by Django 5.2.4 on 2025-07-14 12:23

import ckeditor.fields
import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('date_achieved', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('fee_file', models.FileField(upload_to='fee_structures/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='hero_images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('transition_style', models.CharField(choices=[('fade', 'Fade'), ('zoom', 'Zoom'), ('flip', 'Flip'), ('slide', 'Slide'), ('carousel', 'Carousel'), ('flip3d', 'Flip 3D'), ('mask_reveal', 'Mask Reveal'), ('ken_burns', 'Ken Burns')], default='fade', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavbarAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True, null=True)),
                ('background_color', colorfield.fields.ColorField(default='#ffcc00', image_field=None, max_length=25, samples=None, verbose_name='Background Color')),
                ('text_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None, verbose_name='Text Color')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Navbar Advert',
                'verbose_name_plural': 'Navbar Adverts',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='SchoolCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=20)),
                ('calendar_file', models.FileField(upload_to='calendars/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Kenyan Excellence Academy', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('address', models.TextField(default='Nairobi, Kenya')),
                ('phone', models.CharField(default='+254 700 000 000', max_length=20)),
                ('email', models.EmailField(default='info@school.ac.ke', max_length=254)),
                ('motto', models.CharField(default='Striving for Excellence', max_length=200)),
                ('aim', ckeditor.fields.RichTextField(default='Our aim is to provide quality education...')),
                ('history', ckeditor.fields.RichTextField(default='Founded in 2000...')),
                ('google_map_embed', models.TextField(blank=True, help_text='Paste Google Maps embed code here', null=True)),
                ('navbar_color', colorfield.fields.ColorField(default='#006600', image_field=None, max_length=25, samples=None, verbose_name='Navbar Color')),
                ('footer_color', colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Footer Color')),
                ('navbar_font_color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Navbar Font Color')),
                ('footer_font_color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Footer Font Color')),
                ('body_font', models.CharField(default="'Helvetica Neue', Helvetica, Arial, sans-serif", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Setting',
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('section_type', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('academics', 'Academics Page'), ('admissions', 'Admissions Page'), ('news', 'News Page'), ('events', 'Events Page'), ('achievements', 'Achievements Page'), ('gallery', 'Gallery Page'), ('contact', 'Contact Page')], max_length=50)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('background_color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Background Color')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subsections/')),
                ('background_color', colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=25, samples=None, verbose_name='Background Color')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='school_app.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
